apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
    spec:
      containers:
      - image: 373669830907.dkr.ecr.us-east-1.amazonaws.com/doctransfer/user-service:latest
        name: user-service
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 200m
            memory: 600Mi
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: user-service-configmap
                key: db_host
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: doctransfer-app-postgres-test-password
                key: password
status: {}
